In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
data={
    'Name':['vasu','naveen','yash','sachin','maynk'],
    'Age':[23,None,30,26,None,],
    'City':['Buchawas','Taranagr','Bikaner','jaipur','pali'],
    'Purchased':['yes','no','yes','no','yes']
}
    

In [3]:
df=pd.DataFrame(data)

In [4]:
df

,Name,Age,City,Purchased
0,vasu,23.0,Buchawas,yes
1,naveen,NaN,Taranagr,no
2,yash,30.0,Bikaner,yes
3,sachin,26.0,jaipur,no
4,maynk,NaN,pali,yes


In [5]:
#handling missing values
df.fillna(df['Age'].mean(), inplace=True)

In [6]:
df

,Name,Age,City,Purchased
0,vasu,23.000000,Buchawas,yes
1,naveen,26.333333,Taranagr,no
2,yash,30.000000,Bikaner,yes
3,sachin,26.000000,jaipur,no
4,maynk,26.333333,pali,yes


In [7]:
df=pd.get_dummies(df,columns=['City'], dtype=int)

In [8]:
df

,Name,Age,Purchased,City_Bikaner,City_Buchawas,City_Taranagr,City_jaipur,City_pali
0,vasu,23.000000,yes,0,1,0,0,0
1,naveen,26.333333,no,0,0,1,0,0
2,yash,30.000000,yes,1,0,0,0,0
3,sachin,26.000000,no,0,0,0,1,0
4,maynk,26.333333,yes,0,0,0,0,1


In [9]:
le=LabelEncoder()

In [10]:
df['Purchased']=le.fit_transform(df['Purchased'])

In [11]:
df

,Name,Age,Purchased,City_Bikaner,City_Buchawas,City_Taranagr,City_jaipur,City_pali
0,vasu,23.000000,1,0,1,0,0,0
1,naveen,26.333333,0,0,0,1,0,0
2,yash,30.000000,1,1,0,0,0,0
3,sachin,26.000000,0,0,0,0,1,0
4,maynk,26.333333,1,0,0,0,0,1


In [12]:
scaler=StandardScaler()

In [13]:
df['Age']=scaler.fit_transform(df[['Age']])

In [14]:
df

,Name,Age,Purchased,City_Bikaner,City_Buchawas,City_Taranagr,City_jaipur,City_pali
0,vasu,-1.500751,1,0,1,0,0,0
1,naveen,0.000000,0,0,0,1,0,0
2,yash,1.650826,1,1,0,0,0,0
3,sachin,-0.150075,0,0,0,0,1,0
4,maynk,0.000000,1,0,0,0,0,1


In [15]:
X = df.drop(['Name','Purchased'], axis=1)
y = df['Purchased']


In [16]:
X

,Age,City_Bikaner,City_Buchawas,City_Taranagr,City_jaipur,City_pali
0,-1.500751,0,1,0,0,0
1,0.000000,0,0,1,0,0
2,1.650826,1,0,0,0,0
3,-0.150075,0,0,0,1,0
4,0.000000,0,0,0,0,1


In [17]:
x=df[['Age','City_Bikaner','City_Buchawas','City_Taranagr','City_jaipur','City_pali']]
y=df['Purchased']

In [18]:
x

,Age,City_Bikaner,City_Buchawas,City_Taranagr,City_jaipur,City_pali
0,-1.500751,0,1,0,0,0
1,0.000000,0,0,1,0,0
2,1.650826,1,0,0,0,0
3,-0.150075,0,0,0,1,0
4,0.000000,0,0,0,0,1


In [19]:
y

0    1
1    0
2    1
3    0
4    1
Name: Purchased, dtype: int32

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [21]:
model=LinearRegression()

In [22]:
model.fit(x_test,y_test)

LinearRegression()

In [23]:
model.predict(x_train)

array([0., 0., 0., 0.])

In [24]:
#linear regression
from sklearn.linear_model import LinearRegression
import numpy as np
x=[[2],[3],[4],[5],[6]]
y=[20],[25],[30],[40],[55]
model=LinearRegression()

In [25]:
model.fit(x,y)

LinearRegression()

In [26]:
df=model.predict([[8]])

In [27]:
df

array([[68.]])

In [28]:
from sklearn.linear_model import LogisticRegression
import numpy as np
from sklearn.preprocessing import LabelEncoder


In [29]:
x=[[2],[3],[4],[5]]
y=['fail'],['fail'],['pass'],['pass']

In [30]:
model=LogisticRegression()

In [31]:
lgr=LabelEncoder()

In [32]:
y=lgr.fit_transform(y)

C:\Users\91994\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [33]:
y

array([0, 0, 1, 1], dtype=int64)

In [34]:
model.fit(x,y)

LogisticRegression()

In [35]:
predicts =model.predict([[4]])

In [36]:
if predicts==0:
    print("fail")
else:
    print("pass")



pass


In [37]:
from sklearn.neighbors import KNeighborsClassifier

In [38]:
x=[
    [180,7],
    [190,7.5],
    [230,8],
    [250,8.5],
    [290,9],
    [330,9.3]
]
y=[0,0,0,1,1,1]
model= KNeighborsClassifier(n_neighbors=3)
model.fit(x,y)
weight=float(input("enter the weight in grams:"))
size=float(input("inter size in cm:"))
prediction=model.predict([[weight,size]])[0]
if prediction==0:
    print("ye to aam h ")
else:
    print("ye amrood h ")


enter the weight in grams: 654
inter size in cm: 54


ye amrood h 


In [39]:
from sklearn.metrics import mean_squared_error,mean_absolute_error
import numpy as np
real_score=[90,98,67,89]
predicted_score=[91,92,75,81]
mse=mean_squared_error(real_score,predicted_score)
mae=mean_absolute_error(real_score,predicted_score)
rmse=np.sqrt(mse)
print(mse,mae,rmse)

41.25 5.75 6.422616289332565


In [40]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [41]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [42]:
data={
    "Size_sqrt":[1000,1500,2000,2500,3000],
    "bedrooms":[2,3,3,4,5]
}

In [43]:
df=pd.DataFrame(data)

In [44]:
df

,Size_sqrt,bedrooms
0,1000,2
1,1500,3
2,2000,3
3,2500,4
4,3000,5


In [45]:
minmax=MinMaxScaler()
df_minmax=minmax.fit_transform(df)
print(df_minmax)

[[0.         0.        ]
 [0.25       0.33333333]
 [0.5        0.33333333]
 [0.75       0.66666667]
 [1.         1.        ]]


In [46]:
standrd=StandardScaler()
df_standard=standrd.fit_transform(df)

In [47]:
df_standard

array([[-1.41421356, -1.37281295],
       [-0.70710678, -0.39223227],
       [ 0.        , -0.39223227],
       [ 0.70710678,  0.58834841],
       [ 1.41421356,  1.56892908]])

In [48]:
import pandas as pd 
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
data={
    "color":["Red","Blue","green","blue","Red"]
    
}
df=pd.DataFrame(data)

print(df)
le=LabelEncoder()
labled=le.fit_transform(df)
print(labled) 

   color
0    Red
1   Blue
2  green
3   blue
4    Red
[1 0 3 2 1]


C:\Users\91994\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [49]:
ohe=OneHotEncoder()

In [50]:
encoded=pd.get_dummies(df[["color"]])
print(encoded)

   color_Blue  color_Red  color_blue  color_green
0       False       True       False        False
1        True      False       False        False
2       False      False       False         True
3       False      False        True        False
4       False       True       False        False


In [51]:
#impution 
import pandas as pd
from sklearn.impute import SimpleImputer
df={
    "Age":[7,5,6,None,5],
    "candy":["chocolate","icecream",None,"strawberry","chocolate"]
}    

In [52]:
df=pd.DataFrame(df)
df

,Age,candy
0,7.0,chocolate
1,5.0,icecream
2,6.0,None
3,NaN,strawberry
4,5.0,chocolate


In [53]:
imputer=SimpleImputer(strategy="mean")
df["meaned"]=imputer.fit_transform(df[["Age"]])

In [54]:
df

,Age,candy,meaned
0,7.0,chocolate,7.00
1,5.0,icecream,5.00
2,6.0,None,6.00
3,NaN,strawberry,5.75
4,5.0,chocolate,5.00


In [55]:
# import pandas as pd
# from sklearn.impute import SimpleImputer

# # Our dataset with missing values
# data = {
#     "Age": [7, None, 6, 8, None],
#     "Candy": ["Lollipop", "Chocolate", None, "Gum", "Chocolate"]
# }
# df = pd.DataFrame(data)
# print("Original data:\n", df)

# # 1. Fill Age (numeric) with mean
# imputer_mean = SimpleImputer(strategy="mean")
# df["Age_filled"] = imputer_mean.fit_transform(df[["Age"]])

# # 2. Fill Candy (categorical) with most frequent
# imputer_freq = SimpleImputer(strategy="most_frequent")
# df["Candy_filled"] = imputer_freq.fit_transform(df[["Candy"]])

# print("\nAfter Imputation:\n", df)


In [56]:
import pandas as pd
from sklearn.model_selection import train_test_split
data={
    "size":[1000,1500,2000,2500,3000],
    "bedrooms":[2,3,2,2,4],
    "price":[200000,300000,220000,230000,400000]
}

    


In [57]:
df=pd.DataFrame(data)

In [58]:
df

,size,bedrooms,price
0,1000,2,200000
1,1500,3,300000
2,2000,2,220000
3,2500,2,230000
4,3000,4,400000


In [59]:
x=df[["size","bedrooms"]]
y=df["price"]

In [60]:
x

,size,bedrooms
0,1000,2
1,1500,3
2,2000,2
3,2500,2
4,3000,4


In [61]:
y

0    200000
1    300000
2    220000
3    230000
4    400000
Name: price, dtype: int64

In [62]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [63]:
x_train

,size,bedrooms
4,3000,4
2,2000,2
0,1000,2
3,2500,2


In [64]:
x_train

,size,bedrooms
4,3000,4
2,2000,2
0,1000,2
3,2500,2


In [65]:
x_test

,size,bedrooms
1,1500,3


In [66]:
from sklearn.linear_model import LinearRegression

In [67]:
model=LinearRegression()

In [68]:
model.fit(x,y)

LinearRegression()

In [69]:
new_data=model.predict([[2500,2]])

C:\Users\91994\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [70]:
new_data

array([228260.86956522])

In [71]:
from sklearn.metrics import mean_squared_error,mean_absolute_error

In [72]:
import numpy as np
y_true=np.array([1,0,1,1,1,0,0,1,0])
y_pred=np.array([1,0,1,1,1,0,0,1,0])
print(mean_squared_error(y_true,y_pred))

0.0


In [90]:
import numpy as np
from sklearn.linear_model import LogisticRegression
data={
    'name':['vasu','naveen','sunil','ravi'],
    'sal':[22000,25000,30000,40000],
    'pur':['no','no','yes','yes']
}

In [91]:
import pandas as pd
df=pd.DataFrame(data)

In [92]:
df

,name,sal,pur
0,vasu,22000,no
1,naveen,25000,no
2,sunil,30000,yes
3,ravi,40000,yes


In [93]:
le=LogisticRegression()

In [94]:
x=df[['sal']]
y=df['pur']

In [95]:
x

,sal
0,22000
1,25000
2,30000
3,40000


In [96]:
y

0     no
1     no
2    yes
3    yes
Name: pur, dtype: object

In [97]:
from sklearn.model_selection import train_test_split

In [99]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model=le.fit(x_train,y_train)

In [101]:
new_data=[[40000]]
pred=model.predict(new_data)

C:\Users\91994\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [102]:
pred

array(['yes'], dtype=object)

In [103]:
new_data=model.predict([[45000]])

C:\Users\91994\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [104]:
new_data

array(['yes'], dtype=object)